apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: donotsubmit-bot-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: donotsubmit-bot-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: donotsubmit-bot
